project_id = "qgezrxxsuvqsrozbfrtd"

[functions.ai-chat]
verify_jwt = false

[functions.dvla-lookup]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.send-sms-reminder]
verify_jwt = false

[functions.send-mot-reminder]
verify_jwt = false

[functions.remap-lookup]
verify_jwt = false
